### PR TITLE
Fix examples in 'network' docs

### PR DESCRIPTION
**Pull request by ganicke**
- [x] Couple of bugs in the examples.

### CODE REVIEW

**Comment by pelikhan** [comment]
The packet APIs are outdated and should not be used.

**Comment by ganicke** [comment]
The docs were already there. I just updated them even though they're not used. Delete the **onXxxPacketReceive** docs?

**Comment by pelikhan** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ganicke** [comment]
🗑 deleted 🗑

**Pull request merged**
