### PR TITLE
Character LCD driver support

### PR DESCRIPTION
**Pull request by pelikhan**
basic LCD screen driver support + sim support.

image

### CODE REVIEW

**Comment by pelikhan** [comment]
@ladyada

**Comment by ladyada** [comment]
hiya - i've forgotten, how would this be tested?

**Comment by pelikhan** [comment]
I will have in maker so you can test it with metro/mono LCD. It is using the pins from the guide.

**Comment by pelikhan** [comment]
Tested on hardware.

**Comment by ladyada** [comment]
ok let me know when its ready for me to test!

**Pull request merged**
