### PR TITLE
Additional Features for Robo HAT MM1 board

### PR DESCRIPTION
**Pull request by wallarug**
Ready to push first iteration of Robo HAT MM1 board.

The Robo HAT MM1 is developed and maintained by the Robotics Masters team.   Information about the board can be found on Crowd Supply.

https://www.crowdsupply.com/robotics-masters/robo-hat-mm1

Must be Merged at same time as [PR 290](https://github.com/microsoft/pxt-maker/pull/290) in the `microsoft/pxt-maker` repository

### CODE REVIEW

**Comment by wallarug** [comment]
@peterpanstechland  can also verify working.

**Comment by wallarug** [comment]
> Remove gch file

completed! @pelikhan

**Comment by pelikhan** [comment]
We need to test these changes with a meow bit

**Comment by wallarug** [comment]
Sure.  Is that something you can do @pelikhan ?

Why that board specifically?

**Comment by pelikhan** [comment]
Well we need to test a board with that MPU. I don’t have a computer so this will have to wait till next week.

**Comment by wallarug** [comment]
@pelikhan ,

Is it just the MPU testing that is holding up this being merged in?  

I know the MPU stuff has some issues because the MPU on the Robo HAT is currently not included in the codal-core and due to issue [112](https://github.com/lancaster-university/codal-core/pull/113) over on the codal-core repo.    If that is the case - we can just switch that off / remove acceleratometer features for now until we get approval to update the codal-core.

None of the changes (as far as I am aware) in this merge impact on other boards or functions of the library.

**Comment by pelikhan** [comment]
Best to split PRs in smaller chunks.... and it’s holiday here in US so nothing going on before Tuesday.

**Comment by wallarug** [comment]
Ok, no worries.  I'll check back in on Wednesday.  Thanks for the update.

**Pull request merged**
