### PR TITLE
Make buffer writable for tilemap data

### PR DESCRIPTION
**Pull request by riknoll**
Fixes https://github.com/microsoft/pxt-arcade/issues/1625

Obviously this has memory tradeoffs. I was hoping to only make it writable if the user calls the set tile API, but I can't see a way to check it in the TS. @mmoskal is this okay do you think? Tilemaps are one byte per pixel.

### CODE REVIEW

**Comment by mmoskal** [comment]
It would be really easy to expose the isReadOnly method on buffer - it already exists in C++. Also `const b = data.slice()` should work.

Actually, gimme sec.

**Comment by mmoskal** [comment]
Added method, unfortunately needs to also go in pxt-core for sim.

Maybe it's not worth it for this release, I don't know...

**Comment by riknoll** [comment]
I'll port it over to stable tomorrow. Thanks!

**Comment by riknoll** [comment]
Updated, now with the new API!

**Pull request merged**
