### PR TITLE
Allow targets to override melody definitions

### PR DESCRIPTION
**Pull request by cait1inhennessy**
Also rename "piano.ts" to "music_overrides.ts" - more descriptive.

### CODE REVIEW

**Comment by microsoftsam** [comment]
I don't think music_overrides is a good name necessarily. You're using it in this case to override some definitions, but the file should be descriptive of it's contents.

**Comment by pelikhan** [comment]
This PR is just moving code around. Why do we need this?

**Comment by pelikhan** [comment]
Can we fix this melody for all targets instead having to override it?

**Comment by pelikhan** [comment]
@cait1inhennessy what's the status of this PR?

**Comment by cait1inhennessy** [comment]
This issue was resolved by a different PR.

**Pull request closed without merging**
