### PR TITLE
Add support for 8bit parallel screen connection

### PR DESCRIPTION
**Pull request by mmoskal**
Waits on https://github.com/lancaster-university/codal-stm32/pull/10

### CODE REVIEW

**Comment by mmoskal** [comment]
More codal changes coming https://github.com/lancaster-university/codal-stm32/pull/11

**Comment by mmoskal** [comment]
This should be ready and is required by latest codal-core

**Comment by jamesadevine** [comment]
@pelikhan jacdac-ts is blocked on this PR

**Comment by pelikhan** [comment]
@mmoskal can you look at the conflicts?

**Pull request merged**
