### PR TITLE
Add effects to music "play sound" block

### PR DESCRIPTION
**Pull request by klausw**
These are intended to provide some additional options for games and provide inspiration for custom sounds.

Test program based on using a modified editor with this PR included: https://makecode.com/_4PfMrpP9bg0h

Adapted from this standalone demo: https://makecode.com/_2uac15Pjbig9

### CODE REVIEW

**Comment by jwunderl** [comment]
Here's a custom build w/ direct link to the first project using the new sounds for anyone who wants to test them: https://arcade.makecode.com/app/3bfb35332e97822e5c79e3259627d02af6f5ffc7-2145f7a31c#pub:_4PfMrpP9bg0h

**Review by jwunderl — APPROVED** [review]
Tried all the sounds out on my pygamer+speaker and my meowbit, all sound great on both devices! (footstep is pretty subtle, but that definitely feels intentional / right -- you could actually use it in a game without it being overbearing)

**Review by livcheerful — APPROVED** [review]
wowow i'm so excited!! this is awesome!

**Comment by jwunderl** [comment]
@klausw Thank you so much for adding these, they're fantastic!

**Pull request merged**
