### PR TITLE
Detect accelerometer type

### PR DESCRIPTION
**Pull request by STEMSmartLabs**

### CODE REVIEW

**Comment by mmoskal** [comment]
This should be tested not to hang when there's no accelerometer connected.

**Comment by STEMSmartLabs** [comment]
> This should be tested not to hang when there's no accelerometer connected.

I don't see any blocking call on I2C::read() driver for now.
https://github.com/lancaster-university/codal-core/blob/master/source/driver-models/I2C.cpp

However, I will verify in hardware without accelerometer connected.

**Comment by STEMSmartLabs** [comment]
image

Tested with & without Accelerometer, Received the console output and accelerometer sensing.  Any suggestion ?

**Comment by pelikhan** [comment]
Looks I will merge today.

**Pull request merged**
