### PR TITLE
Top level events for sprites

### PR DESCRIPTION
**Pull request by pelikhan**
Adds top level events for created, destroed, collision, overlap. None of the existing APIs have been removed yet.

Test script: https://makecode.com/_hMuaE7PCxgre

image

### CODE REVIEW

**Comment by riknoll** [comment]
LGTM! What do we want for the updated authoring? Maybe something like this:

```typescript
//% block="on %kind1{0} %sprite1{2} overlap with %kind2{1} %sprite2{3}"
onOverlap(kind1: SpriteKind, kind2: SpriteKind, cb: (sprite1: Sprite, sprite2: Sprite) => void) {

}
```

Where the `{0}` indicates the argument index (which I guess parameters to the callback would also be given)? @samelhusseini what do you think?

**Comment by samelhusseini** [comment]
Looks good @riknoll

**Comment by riknoll** [comment]
Also it would probably be a breaking change for all our targets.

**Comment by pelikhan** [comment]
AAARGG. No. Let's do the curly stuff

**Pull request merged**
