### PR TITLE
regorg music blocks

### PR DESCRIPTION
**Pull request by pelikhan**
image
image

### CODE REVIEW

**Comment by pelikhan** [comment]
@ganicke melody stop needs docs.

**Comment by ganicke** [comment]
Fixed instances only for sounds? Is this a temporary thing? You'll need a screen full of playTones to make your own sounds (melodies).

**Comment by mmoskal** [comment]
that's a good point - we could have a block that plays a string. In TS you can do: `new Melody("a5 ...").play()`

However, the current music blocks also have no way to play a string

**Comment by ganicke** [comment]
Some ``music.createMelody("")`` melody factory. Good way to stress your GC.

**Pull request merged**
