### PR TITLE
Bug 151 fix

### PR DESCRIPTION
**Pull request by caitlin-hennessy**
Resolves https://github.com/Microsoft/pxt-adafruit/issues/151

### CODE REVIEW

**Comment by pelikhan** [comment]
We have to check but there are APIs to do basic math on the colors. Using  the hue comes from the LightLogo APIs which makes it easier to cycle through colors rather than use RGB.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by caitlin-hennessy** [comment]
Waiting on https://github.com/Microsoft/pxt/issues/2742

Need to add second function "setPhotonHue", apply this to scripts with old target version

**Comment by abchatra** [comment]
@caitlin-hennessy what is the status of this PR?

**Comment by pelikhan** [comment]
We've discussed about this and we will have a color wheel color picker on the blocks side.

**Pull request closed without merging**
