### PR TITLE
added feature to render to svg

### PR DESCRIPTION
**Pull request by pelikhan**
Refactoring useful code to render canvas into svg as a datauri.

### CODE REVIEW

**Comment by riknoll** [comment]
Wait, how is this an SVG? Isn't it just an SVG that is embedding a PNG?

**Comment by pelikhan** [comment]
It's an svg:image element that gets updated in the SVG tree.

**Comment by riknoll** [comment]
`toDataURL()` returns an encoded PNG. LGTM but I would rename the function because it's confusing.

**Comment by pelikhan** [comment]
Renamed.

**Pull request merged**
