### PR TITLE
Support for SPI Flash storage and USB MSC

### PR DESCRIPTION
**Pull request by mmoskal**
This utilizes https://github.com/lancaster-university/codal-core/pull/17

When testing this, best use the following bootloader:
[uf2-samd-1.24.zip](https://github.com/lancaster-university/codal-core/files/1571537/uf2-samd-1.24.zip)

I used the following testing program:

```
loops.forever(function () {
    pins.LED.digitalWrite(true)
    loops.pause(500)
    pins.LED.digitalWrite(false)
    loops.pause(200)

    storage.appendCSV("pxt.csv", [control.millis(), input.acceleration(Dimension.X), input.acceleration(Dimension.Y)])
})
```

To test, connect it  to computer, wait a short while for it to log something, disconnect (power down), connect again and look in `SPIFLASH/pxt.csv` on the `CODAL` volume (flash drive).

If you have updated bootloader, you can try flashing by dropping any UF2 file on `CODAL` volume.

There's currently no simulator support.

### CODE REVIEW

**Comment by pelikhan** [comment]
Not seeing any CODAL drive. I'm seeing CPLAYBOOT in bootloader mode, otherwise no drive shows up while the blinky is running (Windows 10)

**Comment by mmoskal** [comment]
@pelikhan could you try testing again, with the new link: https://makecode.adafruit.com/app/f843348e061c6819bb4073fd09a8a87a156e5743-93167adf4d

**Comment by pelikhan** [comment]
No more luck. Can run any tool to give you diagnostics?

**Comment by pelikhan** [comment]
image

**Comment by mmoskal** [comment]
Hmm... it works with my VM, and debugging is rather an iterative process. So I guess I will just get back to this in January.

**Comment by pelikhan** [comment]
@mmoskal can i find you a windows machine ?:)

**Comment by pelikhan** [comment]
Looks the like PR is merged

**Pull request merged**
