### PR TITLE
Tilemap block definitions

### PR DESCRIPTION
**Pull request by shakao**
image

TODO: 
- Go over all examples and ensure they're correct
- Fix bug with using 'location' argument in sprite overlaps tile block

### CODE REVIEW

**Comment by riknoll** [comment]
Would `array of all _____ tile locations` be clearer? Or is that too long?

**Comment by shakao** [comment]
updated blocks:
image

**Comment by pelikhan** [comment]
I think "tile map" should be used consistently across all blocks. Map alone has many meanings.

**Comment by shakao** [comment]
yeah good point, better to be consistent
image

**Comment by riknoll** [comment]
Hmmm..... "tile map" or "tilemap"?

**Comment by riknoll** [comment]
I thought we were doing the tileset field editor as a shadow block?

**Comment by pelikhan** [comment]
also use ``blockGap`` to harmonize the gap

**Pull request merged**
