### PR TITLE
Event to update all sprites of a given kind

### PR DESCRIPTION
**Pull request by jwunderl**
This would be a new block so probably add the [do not merge] tag for me please?

would resolve https://github.com/Microsoft/pxt-arcade/issues/757 @jamesadevine

block sounds a bit wonky but I'm blanking on good wording for it

arcade-screenshot 3

results in

### CODE REVIEW

**Comment by pelikhan** [comment]
Please add docs page as well.

**Comment by abchatra** [comment]
What is the motivation for adding this block?

**Comment by jwunderl** [comment]
This is mainly just a proposal for the behavior requested in https://github.com/Microsoft/pxt-arcade/issues/757. Helps separate concerns from a main `on game update` for different kinds of sprites, and maps to a fairly common behavior - .

**Comment by pelikhan** [comment]
What does the code look like if you do a foreach over the sprite by category? (we have a block for that?)

**Comment by jwunderl** [comment]
Like this:

screen shot 2019-02-27 at 9 37 36 am

spooky mouseless creation

**Comment by jwunderl** [comment]
Closing this one as I don't think it's useful enough to add another block for now, can revisit later

**Pull request closed without merging**
