### PR TITLE
Add gcPreAllocateBlock()

### PR DESCRIPTION
**Pull request by mmoskal**
This needs separate porting to `dev`, so do not merge to `master`

### CODE REVIEW

**Comment by mmoskal** [comment]
@jwunderl thinks this might be missing to fix the build https://github.com/microsoft/pxt-common-packages/pull/859/files

**Comment by pelikhan** [comment]
@mmoskal anything missing here?

**Comment by mmoskal** [comment]
Should be good to go, but this is for microbit branch

**Comment by abchatra** [comment]
Looks good

**Pull request merged**
