### PR TITLE
Use TC4 not TCC0 on SAMD21

### PR DESCRIPTION
**Pull request by mmoskal**
I guess we should check if this fixes I2C?

### CODE REVIEW

**Comment by pelikhan** [comment]
Accelerometer on CPX?

**Comment by mmoskal** [comment]
I mean, I doubt it fixes anything... we just don't need TCC so we can use TC

**Comment by sabas1080** [comment]
Fix I2C??

**Comment by pelikhan** [comment]
All changes are in maker beta, including your touch changes

**Comment by sabas1080** [comment]
ok, reported error in discord with touch, i am going to test I2C

**Pull request merged**
