### PR TITLE
Add some ref docs for 'effects'

### PR DESCRIPTION
**Pull request by ganicke**
- [x] **startEffect** ref page
- [x] **clearParticles** ref page
- [x] **startScreenEffect** ref page
- [x] **endScreenEffect** ref page

### CODE REVIEW

**Comment by ganicke** [comment]
@jwunderl

**Comment by ganicke** [comment]
Feel free to add another example with FIRE!!!

**Comment by jwunderl** [comment]
For sprites/clear-particles can do this:

```typescript
let logs: Sprite = null
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    effects.clearParticles(logs)
    logs.startEffect(effects.bubbles, 1500)
})
logs = sprites.create(img`
    . . . . . . . . . . . . . . . .
    . . . . . . . . . . . . . . . .
    . . . . . . . . . . . . . . . .
    . . . . . . . . . . . . . . . .
    . . . . . . . . . . . . . . . .
    . . . . . . . . . . . . e . . .
    . . e e . . . . . . . e e . . .
    . . . e e e . . . e e d e . . .
    . . . e d e e e . e d e e . . .
    . . . e e d d e e d d e . . . .
    . . . . . e e d d e e . . . . .
    . . . e e d e e d d e . . . . .
    . . e e d d e e e d d e e . . .
    . . e d d e e . e e e d e e . .
    . . e e e . . . . . e e e . . .
    . . . . . . . . . . . . . . . .
`, 0)
logs.startEffect(effects.fire)
```

to create a log fire and extinguish with bubbles!

**Comment by ganicke** [comment]
Ok, I'll undo that last change and add your example.

**Pull request merged**
