### PR TITLE
Use XOrg misc-fixed for font8

### PR DESCRIPTION
**Pull request by mmoskal**
This font includes:
* Latin characters with all sorts of accents (you can finally get my name right!)
* Cyrillic
* Greek
* Half-width Katakana (Japanese)
* a number of arrows and similar symbols
* Hebrew and Arabic (though our text printing is left-to-right only right now)

There is no support for unicode on hardware now, but I'll be adding it.

The source site says it's public domain - http://pelulamu.net/unscii/

### CODE REVIEW

**Comment by jwunderl** [comment]
Could be nice to have unscii-8-thin as an option as well

**Comment by mmoskal** [comment]
Dropping UNASCII - not sure about copyrights. Now using XOrg misc-fixed - see https://en.wikipedia.org/wiki/Fixed_(typeface)

Source: https://www.cl.cam.ac.uk/~mgk25/ucs-fonts.html

This font includes:
* Latin characters with all sorts of accents (you can finally get my name right!)
* Cyrillic
* Greek
* a number of arrows and similar symbols
* Hebrew (though our text printing is left-to-right only right now)

This font:
screen shot 2018-11-19 at 11 52 15

Unascii (previous version of this PR):
screen shot 2018-11-19 at 11 53 40

Current:
screen shot 2018-11-19 at 11 58 31

**Comment by abchatra** [comment]
Do I need file OSS request for  https://www.cl.cam.ac.uk/~mgk25/ucs-fonts.html? Where is the license?

**Comment by mmoskal** [comment]
When you get the tarball, you can look at `.bdf` files, here are the source files:
```
[14:07 ucs-fonts]$ grep COPYRIGHT 6x9.bdf 5x7.bdf
6x9.bdf:COPYRIGHT "Public domain font.  Share and enjoy."
5x7.bdf:COPYRIGHT "Public domain font.  Share and enjoy."
[14:09 ucs-fonts]$
```

I couldn't find any license file.

**Comment by mmoskal** [comment]
BTW, these fonts ship on all desktop Linux machines in existence.

**Comment by mmoskal** [comment]
@abchatra any news on OSS req?

**Comment by abchatra** [comment]
https://ossmsft.visualstudio.com/_oss?requestId=1164649&_a=progress

Sorry just filed.

**Comment by abchatra** [comment]
This is approved by legal. Good to merge.

**Comment by abchatra** [comment]
@mmoskal @riknoll

**Pull request merged**
