### PR TITLE
Support for micro-mqtt

### PR DESCRIPTION
**Pull request by pelikhan**
MQTT bindings over the esp32spi project.

### CODE REVIEW

**Comment by sabas1080** [comment]
interesting, could I test in arduino 1010 wifi?

**Comment by pelikhan** [comment]
We need a driver for the WINC1500.

**Comment by pelikhan** [comment]
WINC1500 UART interface: http://ww1.microchip.com/downloads/en/appnotes/atmel-xxxxx-atwinc1500-at-command_applicatio_note.pdf

**Comment by sabas1080** [comment]
or ublox ESP32 AT commands?? https://github.com/arduino-libraries/WiFiNINA

**Comment by pelikhan** [comment]
The library should work for various WiFi chips. Someone needs to port them to makecode.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pelikhan** [comment]
We will start with ESP32

**Comment by sabas1080** [comment]
compatible with nina firmware? https://github.com/adafruit/nina-fw

**Comment by pelikhan** [comment]
@mmoskal ready to merge in esp32spi

**Pull request merged**
