### PR TITLE
Add new tilemap blocks and reorganize the scene category

### PR DESCRIPTION
**Pull request by riknoll**
This PR does a few things:

1. Ports several blocks from the tilemap extension into the scene category
2. Reorders the scene groups. Mostly just swapped the "Camera" and "Effects" groups
3. Reordered the blocks in the "Camera" group. We never organized them in the first place; they were in random order. Now "camera follow sprite" is on top
4. Created some new groups for the tilemap-related blocks. They are "Tilemaps", "Operations", and "Locations"
5. Adds "destroy all sprites with effect" to the sprites category
6. Deprecates the old "set tilemap to" block and replaces it with a new one with a shadow block

None of these changes require upgrade rules.

There is one "gotcha" if you use this with the existing tilemaps extension where the tilemap shadow blocks from that extension are not compatible with the new blocks in the scene category. I can push a change to the tilemaps extension to fix this (that would require an upgrade rule, but just one that bumps the extension version).

Here is the "destroy all sprites" block:

Here is how the toolbox looks now:

Screen Shot 2021-09-14 at 10 36 37 AM
Screen Shot 2021-09-14 at 10 16 52 AM
Screen Shot 2021-09-14 at 10 16 59 AM
Screen Shot 2021-09-14 at 10 17 13 AM

And here's an upload target: https://arcade.makecode.com/app/4ef11d7a279b78f072c186abf39a614d0b7df901-64b8e2dee4#editor

### CODE REVIEW

**Review by jwunderl — APPROVED** [review]

**Review by abchatra — APPROVED** [review]

**Review by eanders-MS — APPROVED** [review]

**Comment by Jaqster** [comment]
Can we bump the Effects category above Camera?  They were the 2nd section before, and quite widely used.

**Comment by Jaqster** [comment]
I would also rename "Operations" to "Tilemap Operations"

**Comment by Jaqster** [comment]
Also, why is the Array of Tile Locations block not in the Locations category?  I also feel like the Is mySprite Hitting Wall Left boolean block seems like it might fit under Locations better too... seems similar to Tile to Left of mySprite block.

**Comment by Jaqster** [comment]
I'm also thinking about how do we make it clear through these blocks that location = tilemap col, row....
This is a breaking change, so we probably wouldn't do this now, but what if we used "location col, row" instead of "tilemap col, row".  That might make it more clear?

**Review by livcheerful — APPROVED** [review]

**Review by dmonroym — APPROVED** [review]

**Comment by riknoll** [comment]
@jaqster I moved up the effects category, but I want to put it after camera. I would argue that "camera follow sprite" is more widely used than the screen effects. I made all of the other changes you mentioned.

Here's the toolbox now:

**Comment by Jaqster** [comment]
Looks really great!  Let's pull the numbers for Camera vs. Effects as a matter of due diligence.

**Comment by abchatra** [comment]
@riknoll what is the status of this PR?

**Comment by abchatra** [comment]
@riknoll ping!

**Comment by riknoll** [comment]
Sorry, yes, this is good to go!

**Pull request merged**
