### PR TITLE
init commit from arcade, needs heavy linting / reorg

### PR DESCRIPTION
**Pull request by pelikhan**

### CODE REVIEW

**Comment by jwunderl** [comment]
I was planning on linting and changing this a bit more before sending it up, I'll clean it up a bit and move over to a separate package (outside of game) when I'm done working tonight :)

**Comment by pelikhan** [comment]
On a second though, they should definitely be integrated into the sprite api

**Comment by pelikhan** [comment]
@abchatra @riknoll @mmoskal i'm thinking that particles could live in their package and get a dedicated toolbox section when imported. toughts?

**Comment by pelikhan** [comment]
can you move the particles to a separate package? it will give us more time to evolve them.

**Comment by riknoll** [comment]
Yeah, separate package for sure

**Comment by abchatra** [comment]
Yes agree

**Comment by jwunderl** [comment]
If you want it under sprites, maybe a subcategory that pops out, like ``neopixel`` pops out of ``light`` in adafruit? Sprites is very overloaded blocks wise right now

Definitely was planning on moving stuff around and all, just wanted to fix the front page projectiles first

**Pull request merged**
