### PR TITLE
Migrate radio to common packages

### PR DESCRIPTION
**Pull request by pelikhan**
Moving radio code from microbit to common packages.
Requires https://github.com/microsoft/pxt/pull/6431

Note that I have left deprecated APIs in microbit for backward compat. 
There will probably be some C++ update needed to make this compile with CODAL (untested)

### CODE REVIEW

**Comment by pelikhan** [comment]
@mmoskal ready for review. mostly moving files around. Might need to update C++ defines to make it build on arcade.

**Comment by pelikhan** [comment]
We probably need to do the radio—-platform trick to handle MCU that don’t have radio

**Comment by mmoskal** [comment]
Why? You just should not be able to add the radio package on STM

**Comment by mmoskal** [comment]
You could have radio—-dongle though, connected via SPI or maybe jacdac

**Comment by pelikhan** [comment]
I mean we have RPI, SAMD, STM....

**Pull request merged**
