### PR TITLE
patching IR (tested on HW)

### PR DESCRIPTION
**Pull request by pelikhan**
Patch from @jamesadevine

### CODE REVIEW

**Comment by pelikhan** [comment]
TC3 is used by the DAC as well. Looking into using a different channel.

**Comment by mmoskal** [comment]
There are unused channels on the system low level timer. But it would require some api change to use that.

**Comment by jamesadevine** [comment]
https://github.com/Microsoft/pxt-common-packages/pull/736/files#diff-afd3b1716803cee6eade9e78834d5de5R183

Will never be true as we have a 16 bit timer with 1 us precision, so we will wait variable times between sends.

**Comment by jamesadevine** [comment]
Will use system_timer_* instead.

**Comment by jamesadevine** [comment]
@mmoskal I'm using TCC2 for IR timings instead of TC3. I don't think this affects any user facing GPIO.

When it comes to integrating jacdac in the future, we won't be able to run TCC timer at the highest priority (if we run IR at all)

**Pull request merged**
