### PR TITLE
Fix GC assertion

### PR DESCRIPTION
**Pull request by mmoskal**
fixes https://github.com/Microsoft/pxt-microbit/issues/1985

### CODE REVIEW

**Comment by mmoskal** [comment]
inGC() is used in assertions to check that a given pointer was allocated by the GC. It wasn't working for the first pointer allocated in a GC block.

**Comment by abchatra** [comment]
Shortest bug fix I have ever seen.

**Comment by abchatra** [comment]
It is more interesting that repro of the bug is consistent.

**Comment by mmoskal** [comment]
Things are very deterministic in these embedded systems - here there's some randomness from where you press the button and the light level, but I guess it doesn't influence anything.

**Comment by mmoskal** [comment]
I wonder why we were not hitting that before, but I guess we don't trigger this check too often...

**Pull request merged**
